export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const TOGGLE_PLAY_HOVER = 'TOGGLE_PLAY_HOVER';
export const TOGGLE_LOADER = 'TOGGLE_LOADER';
export const TOGGLE_LOGGED = 'TOGGLE_LOGGED';
export const MANAGE_TOKEN = 'MANAGE_TOKEN'